[platformio]
src_dir = src

[env:pro8MHzatmega328]
platform = atmelavr
framework = arduino
board = pro8MHzatmega328

lib_deps =
    EnableInterrupt
    Low-Power
    AskSinPP

build_flags =
    -D SERIALDEBUG
    -D SIMPLE_CC1101_INIT
    -D LED_ENABLED

upload_speed = 57600
monitor_speed = 57600

; EEPROM bei Upload behalten (kein Chip-Erase): Peers/MasterID/State bleiben erhalten
upload_flags = -D
