#!/bin/sh
# WebUI icon used from http://icons8.com 
target="UNDEFINED"
if [ "$1" != "" ]; then
  target=$1
fi
echo $target

if [ "$1" = "CCU2" ]; then
  mount -t ubifs ubi1:user /usr/local
elif [ "$1" = "HM-RASPBERRYMATIC" ] || [ "$1" = "CCU3" ]; then
  if ! mount | grep -q "/usr/local"; then
    mount /usr/local
  fi
fi  

ADDON_NAME=hb-sr-devices-addon
RC_DIR=/usr/local/etc/config/rc.d
WWW_DIR=/usr/local/etc/config/addons/www/$ADDON_NAME
ADDON_DIR=/usr/local/addons/$ADDON_NAME

# Alte Firmware Files löschen
rm -f ${ADDON_DIR}/firmware/rftypes/*

# Startscript anlegen
cp -af rc.d/$ADDON_NAME ${RC_DIR}/
chmod +x ${RC_DIR}/$ADDON_NAME

# Addon-Verzeichnis anlegen
mkdir -p ${ADDON_DIR}
cp -af addon/* ${ADDON_DIR}
chmod 755 ${ADDON_DIR}

# Symbolic Links
rm -rf ${WWW_DIR}
ln -sf ${ADDON_DIR} ${WWW_DIR}

# Installationsstatus entfernen, um Installation nach Reboot zu erzwingen
rm -f ${ADDON_DIR}/installed

sync

# Exit 10 triggers a reboot in CCU addon system
if [ "$1" = "CCU2" ] || [ "$1" = "HM-RASPBERRYMATIC" ] || [ "$1" = "CCU3" ]; then
  exit 10
fi
